services:
  - type: web
    name: whatsapp-requirement-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: WHATSAPP_PROVIDER
        value: evolution_api
      - key: GATEWAY_TYPE
        value: evolution_api
      - key: EVOLUTION_API_URL
        value: "https://whatsapp-gateway-nsr1.onrender.com"
      - key: EVOLUTION_API_KEY
        value: "mysecretkey123"
      - key: EVOLUTION_INSTANCE_NAME
        value: "whatsapp-bot"
      - key: GOOGLE_SHEET_WEBHOOK_URL
        value: "https://script.google.com/macros/s/AKfycby-a2A6tpShmCJjeOVZ-dkNf2POJFiozd6Lz5cC6Krtsbv1qUgVUKq2eKir_DRnrf592A/exec"
      - key: TIMEZONE
        value: Asia/Kolkata
      - key: DEBOUNCE_SECONDS
        value: 1.5
